name: Create release

on:
  push:
    tags:
      - "v*.*.*-*"

jobs:
  bundle_and_upload:
    name: Bundle, upload, and create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: mkdir -p /tmp/files
      - run: tar cfz /tmp/files/authorRequirements.tar.gz --exclude=.git .
      - run: md5sum /tmp/files/authorRequirements.tar.gz > /tmp/files/checksum.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /tmp/files/authorRequirements.tar.gz
            /tmp/files/checksum.txt
    permissions:
      contents: write
