name: Create release

on:
  push:
    tags:
      - "v*.*.*-*"

jobs:
  bundle_and_upload:
    name: Package and upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: mkdir -p /tmp/files
      - run: tar cfz /tmp/files/authorRequirements.tar.gz --exclude=.git .
      - run: md5sum /tmp/files/authorRequirements.tar.gz > /tmp/files/checksum.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/files/authorRequirements.tar.gz
            /tmp/files/checksum.txt
          # Set the body of the release to a list of commit messages since the last release from this branch
          body: |
              $(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"* %s")
    permissions:
      contents: write
